name: test

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/test.yml'
  pull_request:

jobs:
  build:
    name: ${{ matrix.os-name }} (Go ${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go-version:
          - '1.25'
          - '1.26'
        include:
          - os: ubuntu-latest
            os-name: Linux
          - os: macos-latest
            os-name: macOS
          - os: windows-latest
            os-name: Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          cache: true
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: 'go.sum'
      - name: Build
        run: |
          make test
